events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    upstream app_books {
        server books:8080;
    }

    upstream app_authors {
        server authors:8080;
    }

    server {
        listen 80;

        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        location /app-books/ {
            proxy_pass http://app_books/;
            proxy_set_header Host $host;
        }

        location /app-authors/ {
            proxy_pass http://app_authors/;
            proxy_set_header Host $host;
        }
    }
}