server:
  port: 8090

spring:
  application:
    name: app-customers

  config:
    import: "optional:consul:"

  datasource:
    url: jdbc:postgresql://localhost:5432/books20262026
    username: postgres
    password: labcom,2015
    driver-class-name: org.postgresql.Driver

  cloud:
    consul:
      host: ${SPRING_CLOUD_CONSUL_HOST:localhost}
      port: ${SPRING_CLOUD_CONSUL_PORT:8500}
      enabled: true

      discovery:
        enabled: true
        register: true

        tags:
          - traefik.enable=true
          - traefik.http.routers.router-app-customers.rule=PathPrefix(`/app-customers`)
          - traefik.http.routers.router-app-customers.middlewares=middleware-customers
          - traefik.http.middlewares.middleware-customers.stripprefix.prefixes=/app-customers

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true

  prometheus:
    metrics:
      export:
        enabled: true