server:
  port: 8090

spring:
  application:
    name: app-customers

  config:
    import: "optional:consul:"

  datasource:
    url: jdbc:postgresql://localhost:5432/books20262026
    username: postgres
    password: 'labcom,2015'
    driver-class-name: org.postgresql.Driver

  cloud:
    consul:
      enabled: false
      discovery:
        enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true