app.name=app-todo

users.url=https://jsonplaceholder.typicode.com
UserRestClient/mp-rest/url=${users.url}

todos.url=https://jsonplaceholder.typicode.com
TodoSourceRestClient/mp-rest/url=${todos.url}

consul.host=127.0.0.1
consul.port=8500
