CREATE TABLE customer (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email        VARCHAR(255),
    name         VARCHAR(255),
    version      INTEGER,
    CONSTRAINT pk_customer PRIMARY KEY (id)
);

INSERT INTO customer (email, name, version) VALUES ('juan@example.com', 'Juan Pérez', 0);
INSERT INTO customer (email, name, version) VALUES ('maria@example.com', 'María García', 0);
INSERT INTO customer (email, name, version) VALUES ('carlos@example.com', 'Carlos López', 0);
