CREATE TABLE purchaseorder (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    customer_id  BIGINT,
    deliveredon  TIMESTAMP,
    placedon     TIMESTAMP,
    status       INTEGER,
    total        INTEGER,
    version      INTEGER,
    CONSTRAINT pk_purchaseorder PRIMARY KEY (id),
    CONSTRAINT fk_purchaseorder_customer FOREIGN KEY (customer_id) REFERENCES customer(id)
);

INSERT INTO purchaseorder (customer_id, placedon, deliveredon, status, total, version) 
VALUES (1, '2024-01-15 10:00:00', '2024-01-20 14:00:00', 1, 35, 0);

INSERT INTO purchaseorder (customer_id, placedon, deliveredon, status, total, version) 
VALUES (2, '2024-02-03 15:30:00', NULL, 0, 18, 0);

INSERT INTO purchaseorder (customer_id, placedon, deliveredon, status, total, version) 
VALUES (3, '2024-02-10 09:45:00', '2024-02-15 11:20:00', 1, 50, 0);
