global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: authors-app
    scrape_interval: 10s
    metrics_path: /q/metrics
    static_configs:
      # sirve para el escaneo de la maquina que se necesitan las metricas
      - targets: [ 'authors-app:8070' ]

  - job_name: books-app
    scrape_interval: 10s
    metrics_path: /q/metrics
    static_configs:
      # sirve para el escaneo de las metricas de la aplicacion de libros
      - targets: [ 'books-app:8080' ]
